rango/urls.py
from django.urls import path
from rango import views


app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
        views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    # chaper 7 excerise   
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('search/', views.search, name='search'),
    path('goto/', views.goto_url, name='goto'),

] 

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
import datetime

from django.db import models
from django.utils import timezone
# P.97 for slugify
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    # add for chapter 6 p.97
    # slug = models.SlugField()
    # edit it ch6 p.99
    # slug = models.SlugField(blank=True) # p.100 replace it
    # ch6 p.100 we can ensure that the slug field is also unique 
    # by adding the constraint to the slug field. 
    slug = models.SlugField(unique=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    # typo within the admin interface (Categorys, not Categories) can be fixed by adding a nested Meta class 
    # into your model definitions with the verbose_name_plural attribute.
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def __str__(self):
        return self.title
    
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
        return self.user.username

# p.83 Official Tutorial
# https://docs.djangoproject.com/en/2.1/intro/tutorial02/
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):

    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        # fields = ('title', 'url', 'views')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
            # If url is not empty and doesn't start with 'http://',
            # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data  

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)
  

rango/views.py
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from rango.models import Category
from rango.models import Page
# ch7
from rango.forms import CategoryForm
from django.shortcuts import redirect
from django.template.loader import get_template, select_template
# ch7 excercise
from rango.forms import PageForm
# ch9
from django.shortcuts import render
from .forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# ch13
from rango.bing_search import run_query

def index(request):
    """
    Construct a dictionary to pass to the template engine as its context.
    Note the key boldmessage matches to {{ boldmessage }} in the template!
    context_dict = {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!'}
    Return a rendered response to send to the client.
    We make use of the shortcut function to make our lives easier.
    Note that the first parameter is the template we wish to use.

    -------Chapter 6 ----------
    Query the database for a list of ALL categories currently stored.
    Order the categories by the number of likes in descending order.
    Retrieve the top 5 only -- or all if less than 5.
    Place the list in our context_dict dictionary (with our boldmessage!)
    that will be passed to the template engine.
    """

    category_list = Category.objects.order_by(
        '-likes')[:5]  # this shows the top 5 categories
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    # ch10 excercise: still calculating the number of visits, but not render to page
    # Call the helper function to handle the sessions    
    visitor_cookie_handler(request) 
    context_dict['visits'] = request.session['visits']

    # This is using cookies
    # context_dict['visits'] = request.COOKIES.get('visits', '1')
    # Obtain our Response object early so we can add cookie information.
    response = render(request, 'index.html', context=context_dict)

    # Call the helper function to handle the cookies
    # visitor_cookie_handler(request, response)

    # Return response back to the user, updating any cookies that need changed.
    return response


def about(request):

    context_dict = {}
    # Call the helper function to handle the sessions
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']


    response = render(request, 'about.html' ,context=context_dict)
    return response




def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        # updated ch15 - order by views
        pages = Page.objects.filter(category=category).order_by('-views')
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
        # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                # probably better to use a redirect here.
            return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form':form, 'category': category}

    return render(request, 'rango/add_page.html', context_dict)


@login_required
def restricted(request):
    return render(request,'rango/restricted.html')

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                                    'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
    # Update/set the visits cookie
    request.session['visits'] = visits

def search(request):
    result_list = []
    query = ''
    if request.method == 'POST':
        query = request.POST['query'].strip()
    if query:
    # Run our Bing function to get the results list!
        result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list})

def goto_url(request):
   
    if request.method == 'GET':
        page_id = request.GET.get('page_id')
        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))
        selected_page.views = selected_page.views + 1
        selected_page.save()
        return redirect(selected_page.url)
    
    return redirect(reverse('rango:index'))

templates/rango/add_category.html
{% extends 'base.html' %}

{% block title %}
    Add a Category - Rango
{% endblock %}

{% block body_block %}

<div class="jumbotron p-4">

    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
            <!-- This is a Cross-Site Request Forgery (CSRF) token, which helps to protect and secure the HTTP POST request that is initiated on the subsequent submission of a form. -->
            {% csrf_token %} 

            <!-- The need for hidden as well as visible form fields are necessitated by the fact that HTTP is a stateless protocol. -->
            {% for hidden in form.hidden_fields %} 
                {{ hidden }} 
            {% endfor %} 
        
            <!-- The visible fields (those that will be displayed to the user) are controlled by the fields attribute within your ModelForm Meta class. -->
            {% for field in form.visible_fields %} 
                {{ field.errors }} 
                {{ field.help_text }} 
                {{ field }} 
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
    
</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'base.html' %}

{% block title %}
    Add a Category - Rango
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />

            <button class="btn btn-primary" type="submit" name="submit">
                Add Page
            </button>
            <div class="p-5"></div>
                
        </form>        
           
    </div>
</div>	
{% endblock %}

templates/rango/categories.html
<ul>
 {% if categories %}
  {% for c in categories %}
    {% if c == current_category %}
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
        <span data-feather="archive"></span>{{ c.name }}
      </a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
      <span data-feather="archive"></span>{{ c.name }}
      </a>
    </li>
    {% endif %}
  {% endfor %}
 {% else %}
 <li class="nav-item">There are no categories present.</li>
 {% endif %}
 </ul>
    
  

templates/rango/category.html
{% extends 'base.html' %}

{% block title %}
  {% if category %}
    {{ category.name }}
  {% else %}
    Unknown Category
  {% endif %}
{% endblock %}

 
{% block body_block %}  

<div class="jumbotron p-4">
    
  {% if category %}
    <h1>{{ category.name }}</h1>
    
    {% if pages %}
      <ul>
        {% for page in pages %}
          <li>
            <a href="{{ page.url }}">{{ page.title }}</a>
            {% if page.views > 1 %}
              ({{ page.views }} views)
            {% elif page.views == 1 %}
              ({{ page.views }} view)
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <strong>No pages currently in category.</strong>
    {% endif %} 

    <!--Restricted for login user-->
    {% if user.is_authenticated %}
      <a href="{% url 'rango:add_page' category.slug %}">Add a new page</a>
    {% endif %}
    
  {% else %}
      The specified category does not exist.
  {% endif %}
  
</div>    
{% endblock %}  

templates/rango/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Login
{% endblock %}


{% block body_block %}  

<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>

{% endblock %}

templates/rango/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Register
{% endblock %}

{% block body_block %}  


<h1>Register for Rango</h1>

{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
Rango says: <strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'rango:register' %}"
enctype="multipart/form-data">
    
    {% csrf_token %}
    <!-- Display each form -->
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}


{% endblock %}

templates/rango/restricted.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Restricted
{% endblock %}


{% block body_block %}  

{% if user.is_authenticated %}
    <h1>Restricted Page</h1>
    <p>Since you're logged in, you can see this text!</p>
{% else %}
    <h1>Restricted Page</h1>
    <p>Since you're not logged in, you can't see this text!</p>
{% endif %}

{% endblock %}

templates/rango/search.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} Search {% endblock %}


{% block body_block %}
<div>
  <h1>Search with Rango</h1>
  <br />
  <form
    class="form-inline"
    id="user_form"
    method="post"
    action="{% url 'rango:search' %}"
  >
    {% csrf_token %}
    <div class="input-group">
      <input
        class="form-control"
        type="text"
        size="50"
        name="query"
        value=""
        id="query"
      />
    </div>
    <button class="btn btn-primary" type="submit" name="submit" value="Search">
      Search
    </button>
  </form>
  <div>
    {% if result_list %}
    <h3>Results</h3>
    <!-- Display search results in an ordered list -->
    <div class="list-group">
      {% for result in result_list %}
      <div class="list-group-item">
        <h4 class="list-group-item-heading">
          <a href="{{ result.link }}">{{ result.title }}</a>
        </h4>
        <p class="list-group-item-text">{{ result.summary }}</p>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}