rango/urls.py
from django.urls import path
from rango import views


app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
        views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    # chaper 7 excerise   
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('search/', views.search, name='search'),
    path('goto/', views.goto_url, name='goto'),

] 

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Rango - About
{% endblock %}


{% block body_block %}

        <h1>Rango says...</h1>
        <p>here is the about page.</p> 
        <h2>Show visits</h2>
        <p>Visits: {{ visits }}</p>       
        
        <p>This tutorial has been put together by <your-name>.</p>
        <img src="{{ MEDIA_URL }}owl.jpg" alt="Picture of an Owl."/>

{% endblock %}

templates/add_category.html
<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Add a Category</h1>
    <div>
      <form id="category_form" method="post" action="/rango/add_category/">
        <!-- This is a
        Cross-Site Request Forgery (CSRF) token, which helps to protect and secure the
        HTTP POST request that is initiated on the subsequent submission of a form. -->
        {% csrf_token %} 

        <!-- The need for hidden as well as visible form fields are necessitated by the
        fact that HTTP is a stateless protocol. -->
        {% for hidden in form.hidden_fields %} 
            {{ hidden }} 
        {% endfor %} 
        
        <!-- The visible fields (those that will be displayed to the user) are controlled by the
        fields attribute within your ModelForm Meta class. -->
        {% for field in form.visible_fields %} 
            {{ field.errors }} 
            {{ field.help_text }} 
            {{ field }} 
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
      </form>
    </div>
  </body>
</html>

templates/base-old.html
{% load static %}
{% load rango_template_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <header>
        <h1>Rango website</h1>
    </header>

    <nav>
        <ul>            
            <li><a href="{% url 'rango:about' %}">About</a></li>
        </ul>
    </nav>
    
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
        

    <main>
        <!--This is a django predefine block-->
        {% block content %} {% endblock %}
        <!--This is a custom block-->
        {% block body_block %} {% endblock %}
    </main>

    <hr />

    <footer>
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <!-- Show these links when the user is logged in -->
                    <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index'%}">Logout</a></li>
                    <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
                {% else %}
                    <!-- Show these links when the user is NOT logged in -->
                    <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}

                <!-- Outside the conditional statements, ALWAYS show -->
                
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
                
            </ul>                         
        </div>
        <p>&copy; 2023 Ying Ting Rango Website. All rights reserved.</p>
    </footer>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:search' %}">Search</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>   

templates/catagory.html
<html>
  <head>
    <title>Rango</title>
  </head>
  <body>
    <div>
      {% if category %}
      <h1>{{ category.name }}</h1>
      {% if pages %}
      <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <strong>No pages currently in category.</strong>
      {% endif %} {% else %} The specified category does not exist. {% endif %}
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title_block %}
		HomePage
{% endblock %}


{% block body_block %}    

<div class="jumbotron p-5">
  <div class="container">
        <h1 class="jumbotron-heading">Rango says...</h1>
        <div>
          <h2 class="h2">
            {% if user.is_authenticated %}
              howdy {{ user.username }}!
            {% else %}
              hey there partner!
            {% endif %}
          </h2>
          <strong>{{ boldmessage }}</strong>
        </div>
  </div>
 </div><!--end jumbotron p-5-->

  
	
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card mb-6">
          <div class="card-body">
            <h4>Most Liked Categories</h4>
            <p>
                  {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                            <li class="list-group-item">
                              <a href="{% url 'rango:show_category' category.slug %}">
                                {{ category.name }}</a>
                                
                              <span class="badge badge-pill badge-primary">{{category.likes}}</span>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}
            
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card mb-6">
          <div class="card-body">
            <h4>Most Viewed Pages</h4>
            <p>
            {% if pages %}
            <ul class="list-group">
            {% for page in pages %}
            <li class="list-group-item">
                <a href="{{ page.url }}">{{ page.title }}</a>
                <span class="badge badge-pill badge-primary">{{page.views}}</span>
            </li>
            {% endfor %}
            </ul>
            {% else %}
            <strong>There are no categories present.</strong>
          {% endif %}
            </p>
          </div>
        </div>
      </div>
    </div>	

    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img src="{% static 'images/cat.jpg' %}" alt="Picture of Rango" />    
        </div>  
      </div>  
    </div>
  </div>
</div>
{% endblock %}